name: Trigger Views

on:
  schedule:
    - cron: '30 18 * * *'  # Runs daily at 18:30 UTC (00:00 IST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  trigger-views:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["pypy3.10", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Trigger.py script
        run: python Trigger.py
